"use client";

import { useEffect, useMemo, useState } from "react";
import { Camera, ChevronLeft, ChevronRight, Flag, History, Plus, Settings2, Sparkles, Swords, Trophy, UserPlus, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { holeState, matchPosition, nextHole, playingOrder, strokesOnHole } from "@/lib/scoring";
import { isSupabaseConfigured, supabase } from "@/lib/supabase";
import { signIn, signOut, signUp } from "@/lib/press-data";

type Player = { id: number; name: string; handicap: number; team: "A" | "B" };
const defaultPlayers: Player[] = [
  { id: 1, name: "Golfer 1", handicap: 0, team: "A" }, { id: 2, name: "Golfer 2", handicap: 0, team: "A" },
  { id: 3, name: "Golfer 3", handicap: 0, team: "B" }, { id: 4, name: "Golfer 4", handicap: 0, team: "B" },
];
const pars = [4,4,3,5,4,4,5,3,4,4,5,4,3,4,4,5,3,4];
const indexes = [7,3,15,1,11,5,17,13,9,8,4,12,16,2,10,6,18,14];
const holes = pars.map((par,i)=>({number:i+1,par,stroke:indexes[i]}));
const formats = ["Betterball Match Play","Fourball Match Play","Betterball Stableford","Individual Stableford","Combined Stableford","Stroke Play","Skins"];
const banter = ["Confidence: suspiciously high for this early in the round.","The scorecard has been warned. The trees have not.","Four golfers. Eighteen holes. Several creative explanations.","No gimmes were harmed in the making of this match."];

export default function Home(){
 const [screen,setScreen]=useState<"home"|"setup"|"play"|"history"|"profile">("home"); const [step,setStep]=useState(1);
 const [players,setPlayers]=useState<Player[]>(defaultPlayers); const [course,setCourse]=useState("Wingate Park Country Club"); const [format,setFormat]=useState(formats[0]);
 const [startingHole,setStartingHole]=useState(1); const [currentHole,setCurrentHole]=useState(0); const [scores,setScores]=useState<Record<number,Record<number,number>>>({}); const [presses,setPresses]=useState<number[]>([]); const [toast,setToast]=useState("");
 const [userEmail,setUserEmail]=useState(""); const [authMode,setAuthMode]=useState<"signin"|"signup">("signin"); const [authName,setAuthName]=useState(""); const [authEmail,setAuthEmail]=useState(""); const [authPassword,setAuthPassword]=useState(""); const [authMessage,setAuthMessage]=useState("");
 useEffect(()=>{const saved=localStorage.getItem("the-press-state");if(saved){try{const data=JSON.parse(saved);if(data.players)setPlayers(data.players)}catch{}}},[]);
 useEffect(()=>localStorage.setItem("the-press-state",JSON.stringify({players})),[players]);
 useEffect(()=>{if(!supabase)return;void supabase.auth.getSession().then(({data})=>setUserEmail(data.session?.user.email||""));const {data}=supabase.auth.onAuthStateChange((_event,session)=>setUserEmail(session?.user.email||""));return()=>data.subscription.unsubscribe()},[]);
 const hole=holes[currentHole], holeScores=scores[hole?.number]||{};
 const completedHoles=useMemo(()=>holes.filter(h=>holeState(h.number,hole?.number??1,players.map(p=>p.id),scores)==="complete").map(h=>h.number),[scores,players,hole?.number]);
 const match=useMemo(()=>{const position=matchPosition(completedHoles,players,scores,holes);return position.difference===0?"ALL SQUARE":`${Math.abs(position.difference)} UP · TEAM ${position.difference>0?"A":"B"}`},[completedHoles,scores,players]);
 const score=(id:number,n:number)=>setScores(old=>({...old,[hole.number]:{...(old[hole.number]||{}),[id]:Math.max(1,n)}}));
 const say=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2600)};
 const submitAuth=async()=>{setAuthMessage("");try{if(authMode==="signup"){await signUp(authEmail,authPassword,authName);setAuthMessage("Profile created. Check your email if confirmation is required.")}else{await signIn(authEmail,authPassword);setAuthMessage("Welcome back. The clubhouse remembers you.")}}catch(error){setAuthMessage(error instanceof Error?error.message:"Account action failed.")}};
 const goNext=()=>{const missing=players.filter(p=>!scores[hole.number]?.[p.id]).map(p=>p.name);if(missing.length){say(`${missing.join(", ")} ${missing.length===1?"still needs a score":"still need scores"}.`);return}const number=nextHole(hole.number,startingHole);setCurrentHole(number-1)};
 const goPrevious=()=>{const order=playingOrder(startingHole);const index=order.indexOf(hole.number);setCurrentHole(order[Math.max(0,index-1)]-1)};
 return <main className="min-h-dvh pb-24">
  <header><div className="header-inner"><button onClick={()=>setScreen("home")} className="brand"><span><Flag/></span><b>THE PRESS<small>Golf. Grudges. Glory.</small></b></button><button onClick={()=>setScreen("profile")} className="avatar" aria-label="Open golfer profile">{userEmail?userEmail.slice(0,2).toUpperCase():"GO"}</button></div></header>
  {screen==="home"&&<div className="wrap home">
   <section className="hero"><p className="eyebrow"><Sparkles/> Ready to create evidence?</p><h1>BAD GOLF.<br/><em>GREAT COMPETITION.</em></h1><p>{banter[new Date().getDay()%banter.length]}</p><Button onClick={()=>{setScreen("setup");setStep(1)}} className="main-cta"><Plus/> START A NEW GAME</Button></section>
   <section className="action-grid"><Action icon={<History/>} title="Past crimes" sub="Rounds & permanent evidence" onClick={()=>setScreen("history")}/><Action icon={<Trophy/>} title="Leaderboard" sub="Champions, chokers & excuses"/><Action icon={<Users/>} title="The usual suspects" sub={`${players.length} golfers saved`}/></section>
   <div className="section-title"><div><p className="eyebrow">Last round</p><h2>THE 2 & 1 INCIDENT</h2></div><span className="stamp">SETTLED</span></div>
   <article className="result"><div><small className="winner">THE EVIDENCE LOCKER</small><h3>No completed rounds yet</h3><p>Your first result will be preserved here—excuses included.</p></div><div className="big-result">0<span>&</span>0</div><div className="right"><small>STATUS</small><h3>Clean slate</h3><p>Enjoy it while it lasts.</p></div></article>
  </div>}
  {screen==="setup"&&<div className="wrap setup"><div className="setup-head"><button onClick={()=>step>1?setStep(step-1):setScreen("home")}><ChevronLeft/>Back</button><span>STEP {step} OF 3</span></div><div className="progress">{[1,2,3].map(s=><i className={s<=step?"on":""} key={s}/>)}</div>
   {step===1&&<section><p className="eyebrow"><Flag/> The battlefield</p><h1 className="setup-title">WHERE ARE WE LOSING BALLS?</h1><label>Golf course</label><input className="big-input" value={course} onChange={e=>setCourse(e.target.value)}/><label className="start-label">Starting hole</label><div className="start-options"><button className={startingHole===1?"selected":""} onClick={()=>setStartingHole(1)}>HOLE 1</button><button className={startingHole===10?"selected":""} onClick={()=>setStartingHole(10)}>HOLE 10</button></div><div className="scan"><span><Camera/></span><div><b>Photograph the scorecard</b><p>We’ll create the holes, pars and stroke indexes. You confirm everything before play.</p></div><Button variant="outline" onClick={()=>say("Scorecard scanning is next on the tee sheet.")}>SCAN</Button></div><div className="course-preview"><span>18 HOLES</span><b>PAR 72</b><span>STARTING ON {startingHole}</span></div></section>}
   {step===2&&<section><p className="eyebrow"><Users/> Today’s victims</p><h1 className="setup-title">PICK YOUR FOURBALL</h1><div className="players">{players.map(p=><div className="player" key={p.id}><span className={`team t${p.team}`}>{p.team}</span><input value={p.name} onFocus={e=>e.currentTarget.select()} onChange={e=>setPlayers(players.map(x=>x.id===p.id?{...x,name:e.target.value}:x))}/><div className="hcp"><small>PLAYING HCP</small><button onClick={()=>setPlayers(players.map(x=>x.id===p.id?{...x,handicap:Math.max(0,x.handicap-1)}:x))}>−</button><b>{p.handicap}</b><button onClick={()=>setPlayers(players.map(x=>x.id===p.id?{...x,handicap:x.handicap+1}:x))}>+</button></div><button className="swap" onClick={()=>setPlayers(players.map(x=>x.id===p.id?{...x,team:x.team==="A"?"B":"A"}:x))}>TEAM {p.team}</button></div>)}</div><button className="add"><UserPlus/> Add another golfer</button><p className="tip">Playing handicap is entered manually for today’s course. No index calculations. No nonsense.</p></section>}
   {step===3&&<section><p className="eyebrow"><Swords/> Choose your weapon</p><h1 className="setup-title">HOW ARE WE FIGHTING?</h1><div className="formats">{formats.map(f=><button key={f} onClick={()=>setFormat(f)} className={format===f?"selected":""}>{f}{format===f&&<span>✓</span>}</button>)}</div><div className="rules"><Settings2/><div><b>Press rules</b><p>Manual press · starts on the next hole · unlimited presses</p></div><strong>ON</strong></div></section>}
   <Button onClick={()=>step<3?setStep(step+1):(setScreen("play"),setCurrentHole(startingHole-1))} className="next">{step<3?"NEXT":"LET THE NONSENSE BEGIN"}<ChevronRight/></Button>
  </div>}
  {screen==="play"&&hole&&<div className="wrap play"><div className="score-hero"><div><p>{course}</p><h1>HOLE {hole.number}</h1><span>PAR {hole.par} · STROKE {hole.stroke}</span></div><div><small>{format}</small><b>{match}</b><span>{presses.length?`${presses.length} ACTIVE PRESS${presses.length>1?"ES":""}`:"NO ACTIVE PRESS"}</span></div></div><div className="hole-legend"><span><i className="legend-current"/>Current</span><span><i className="legend-complete"/>Complete</span><span><i className="legend-partial"/>Incomplete</span></div><div className="hole-strip">{holes.map((h,i)=>{const state=holeState(h.number,hole.number,players.map(p=>p.id),scores);return <button key={h.number} aria-label={`Hole ${h.number}, ${state}`} onClick={()=>setCurrentHole(i)} className={state}>{state==="complete"?"✓":""}{h.number}</button>})}</div>
   <div className="score-grid">{players.map(p=>{const val=holeScores[p.id]||hole.par,shots=strokesOnHole(p.handicap,hole.stroke);return <article className="score-player" key={p.id}><div className="player-top"><span className={`team t${p.team}`}>{p.team}</span><div><h3>{p.name}</h3><p>HCP {p.handicap} · {shots?`${shots} shot${Math.abs(shots)>1?"s":""}`:"no shot"}</p></div><div className="net"><small>NET</small><b>{val-shots}</b></div></div><div className="score-controls"><button onClick={()=>score(p.id,val-1)}>−</button><b className={!holeScores[p.id]?"pending-score":""}>{holeScores[p.id]??"–"}</b><button onClick={()=>score(p.id,val+1)}>+</button></div></article>})}</div>
   <div className="play-actions"><Button variant="outline" onClick={goPrevious}><ChevronLeft/>Previous</Button><Button className="press" onClick={()=>{setPresses(x=>[...x,hole.number]);say("PRESS ACCEPTED — somebody is panicking.")}}><Swords/>PRESS!</Button><Button className="next-hole" onClick={goNext}>Next hole<ChevronRight/></Button></div><div className="banter"><small>LIVE FROM THE FAIRWAY</small><p>{completedHoles.length<5?"Plenty of golf left. Unfortunately, you’ll have to play it.":match==="ALL SQUARE"?"All square. Nobody has earned the right to be loud yet.":`${match}. The losing team is checking the handicap maths.`}</p></div>
  </div>}
  {screen==="history"&&<div className="wrap history"><button className="back" onClick={()=>setScreen("home")}><ChevronLeft/>Back</button><p className="eyebrow"><History/> Permanent evidence</p><h1 className="setup-title">PAST CRIMES</h1><div className="empty"><Trophy/><h3>This is where the legends will pile up.</h3><p>Finish your first round and it will join the evidence locker.</p></div></div>}
  {screen==="profile"&&<div className="wrap profile-screen"><button className="back" onClick={()=>setScreen("home")}><ChevronLeft/>Back</button><p className="eyebrow"><Users/> Your clubhouse identity</p><h1 className="setup-title">GOLFER PROFILE</h1>{!isSupabaseConfigured?<div className="connection-card"><Sparkles/><div><b>Account system prepared</b><p>The screens, database and security are ready. Connect the new Supabase project to activate registrations and shared rounds.</p></div></div>:userEmail?<div className="profile-card"><div className="profile-avatar">{userEmail.slice(0,2).toUpperCase()}</div><div><small>SIGNED IN AS</small><h2>{userEmail}</h2><p>Your rounds, scores and sporting crimes will follow you across devices.</p></div><Button variant="outline" onClick={async()=>{await signOut();setAuthMessage("Signed out.")}}>SIGN OUT</Button></div>:<div className="auth-card"><div className="auth-tabs"><button className={authMode==="signin"?"active":""} onClick={()=>setAuthMode("signin")}>SIGN IN</button><button className={authMode==="signup"?"active":""} onClick={()=>setAuthMode("signup")}>CREATE PROFILE</button></div>{authMode==="signup"&&<><label>Display name</label><input value={authName} onChange={e=>setAuthName(e.target.value)} placeholder="Your name"/></>}<label>Email</label><input type="email" value={authEmail} onChange={e=>setAuthEmail(e.target.value)} placeholder="you@example.com"/><label>Password</label><input type="password" value={authPassword} onChange={e=>setAuthPassword(e.target.value)} placeholder="At least 8 characters"/><Button className="next" onClick={submitAuth}>{authMode==="signup"?"CREATE MY PROFILE":"ENTER THE CLUBHOUSE"}</Button>{authMessage&&<p className="auth-message">{authMessage}</p>}</div>}</div>}
  {toast&&<div className="toast">{toast}</div>}<nav><button onClick={()=>setScreen("home")} className={screen==="home"?"active":""}><Flag/>Home</button><button onClick={()=>{setScreen("setup");setStep(1)}} className={screen==="setup"?"active":""}><Plus/>New game</button><button onClick={()=>setScreen("history")} className={screen==="history"?"active":""}><History/>History</button><button><Trophy/>Table</button></nav>
 </main>
}

function Action({icon,title,sub,onClick}:{icon:React.ReactNode,title:string,sub:string,onClick?:()=>void}){return <button className="action" onClick={onClick}>{icon}<span><b>{title}</b><small>{sub}</small></span><ChevronRight/></button>}
